# Generated by Django 4.2.16 on 2026-04-22 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', '学生'), ('teacher', '任课教师')], max_length=10, verbose_name='在班角色')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
            ],
            options={
                'verbose_name': '班级成员',
                'verbose_name_plural': '班级成员',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='班级名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='班级简介')),
                ('grade', models.CharField(blank=True, default='', max_length=40, verbose_name='年级')),
                ('invite_code', models.CharField(blank=True, max_length=12, unique=True, verbose_name='邀请码')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('head_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headed_classes', to=settings.AUTH_USER_MODEL, verbose_name='班主任')),
                ('members', models.ManyToManyField(blank=True, related_name='joined_classes', through='classes.ClassMember', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '班级',
                'verbose_name_plural': '班级',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='课程名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='课程简介')),
                ('cover_color', models.CharField(default='#1677ff', help_text='如 #1677ff，用于课程卡片主色', max_length=20, verbose_name='封面主题色')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='classes.classroom', verbose_name='所属班级')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_courses', to=settings.AUTH_USER_MODEL, verbose_name='授课教师')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='classmember',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='classes.classroom'),
        ),
        migrations.AddField(
            model_name='classmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='classmember',
            unique_together={('classroom', 'user')},
        ),
    ]
