# Generated by Django 4.2.16 on 2026-04-22 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussionTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='主题标题')),
                ('content', models.TextField(verbose_name='主题内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_topics', to=settings.AUTH_USER_MODEL, verbose_name='发帖人')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='classes.course', verbose_name='所属课程')),
            ],
            options={
                'verbose_name': '讨论主题',
                'verbose_name_plural': '讨论主题',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscussionReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='回复内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='回复时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_replies', to=settings.AUTH_USER_MODEL, verbose_name='回复人')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='classes.discussiontopic', verbose_name='所属主题')),
            ],
            options={
                'verbose_name': '讨论回复',
                'verbose_name_plural': '讨论回复',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='公告标题')),
                ('content', models.TextField(verbose_name='公告内容')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='置顶')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_announcements', to=settings.AUTH_USER_MODEL, verbose_name='发布者')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='classes.course', verbose_name='所属课程')),
            ],
            options={
                'verbose_name': '课程公告',
                'verbose_name_plural': '课程公告',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
    ]
