# Generated by Django 4.2.16 on 2026-04-22 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='试卷标题')),
                ('description', models.TextField(blank=True, null=True, verbose_name='试卷描述')),
                ('duration', models.IntegerField(default=60, verbose_name='考试时长（分钟）')),
                ('is_published', models.BooleanField(default=False, verbose_name='是否发布')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='papers', to='classes.course', verbose_name='所属课程')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '试卷',
                'verbose_name_plural': '试卷',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('single_choice', '单选题'), ('multiple_choice', '多选题'), ('judgment', '判断题'), ('short_answer', '简答题')], max_length=20, verbose_name='题型')),
                ('subject', models.CharField(blank=True, default='', help_text='如：数据结构、高等数学', max_length=60, verbose_name='科目/学科')),
                ('content', models.TextField(verbose_name='题目内容')),
                ('options', models.TextField(blank=True, help_text='每行一个，如：A.选项1', null=True, verbose_name='选项')),
                ('answer', models.TextField(help_text='多选题用英文逗号分隔，如 A,B', verbose_name='标准答案')),
                ('score', models.FloatField(default=5.0, verbose_name='分值')),
                ('explanation', models.TextField(blank=True, default='', help_text='教师添加的错题讲解，学生在错题集中可见', verbose_name='题目讲解')),
                ('keyword_points', models.TextField(blank=True, default='', help_text='JSON 数组，例如 [{"keyword":"循环","weight":0.5}]', verbose_name='主观题关键词得分点')),
                ('similarity_threshold', models.FloatField(default=0.6, help_text='0-1，越高评分越严格', verbose_name='主观题相似度阈值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '试题',
                'verbose_name_plural': '试题',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective_score', models.FloatField(default=0, verbose_name='客观题得分')),
                ('subjective_score', models.FloatField(default=0, verbose_name='主观题得分')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='总得分')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('unfinished', '未完成'), ('finished', '已提交待批阅'), ('graded', '批阅完成')], default='unfinished', max_length=20)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_records', to='exams.exampaper')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'paper')},
            },
        ),
        migrations.AddField(
            model_name='exampaper',
            name='questions',
            field=models.ManyToManyField(to='exams.question', verbose_name='包含试题'),
        ),
        migrations.CreateModel(
            name='AnswerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_answer', models.TextField(blank=True, null=True, verbose_name='学生答案')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='是否正确')),
                ('similarity', models.FloatField(blank=True, help_text='仅主观题：0-1', null=True, verbose_name='语义相似度')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='该题得分')),
                ('auto_score', models.FloatField(blank=True, null=True, verbose_name='自动给分（建议分）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='答题时间')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.question', verbose_name='试题')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.examrecord', verbose_name='考试记录')),
            ],
            options={
                'verbose_name': '答题记录',
                'verbose_name_plural': '答题记录',
                'unique_together': {('record', 'question')},
            },
        ),
        migrations.CreateModel(
            name='WrongQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='重点收藏')),
                ('note', models.TextField(blank=True, default='', verbose_name='学生备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('answer_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wrong_entries', to='exams.answerrecord')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrong_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '错题',
                'verbose_name_plural': '错题',
                'ordering': ['-created_at'],
                'unique_together': {('student', 'question')},
            },
        ),
    ]
