# Generated by Django 4.2.16 on 2026-04-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampaper',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text='过期后学生不可再作答；留空表示无截止', null=True, verbose_name='截止时间'),
        ),
    ]
