# Generated by Django 4.2.16 on 2026-04-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_exampaper_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='examrecord',
            name='switch_tab_count',
            field=models.PositiveIntegerField(default=0, verbose_name='切屏次数'),
        ),
    ]
