# Generated by Django 4.2.16 on 2026-04-22 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('single_choice', '单选题'), ('multiple_choice', '多选题'), ('judgment', '判断题'), ('short_answer', '简答题')], max_length=20, verbose_name='题型')),
                ('similarity_threshold', models.FloatField(default=0.6, verbose_name='相似度阈值')),
                ('weight', models.FloatField(default=1.0, verbose_name='评分权重')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '阅卷规则',
                'verbose_name_plural': '阅卷规则',
            },
        ),
        migrations.CreateModel(
            name='SubjectiveScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity', models.FloatField(verbose_name='语义相似度')),
                ('auto_score', models.FloatField(verbose_name='自动建议分')),
                ('manual_score', models.FloatField(verbose_name='人工最终分')),
                ('graded_at', models.DateTimeField(auto_now_add=True, verbose_name='批阅时间')),
                ('graded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='批阅人')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.question', verbose_name='试题')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjective_scores', to='exams.examrecord', verbose_name='考试记录')),
            ],
            options={
                'verbose_name': '主观题评分记录',
                'verbose_name_plural': '主观题评分记录',
                'unique_together': {('record', 'question')},
            },
        ),
    ]
